
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  datasource:
    username: coupon
    password: '!1234qwer'
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

logging:
  file:
    path: /app/coupon/logs